language: java

jdk: openjdk8

env: DISPLAY=:99.0

services:
  - docker
  - xvfb

# skipping installation step
install: true

script:
  - cd schoolexample
  - mvn clean verify

cache:
  directories:
    - $HOME/.m2