language: java

jdk: openjdk8

env: DISPLAY=:99.0

services:
  - docker

# skipping installation step
install: true

before_script:
  - sh -e /etc/init.d/xvfb start

script:
  - cd schoolexample
  - mvn clean verify

cache:
  directories:
    - $HOME/.m2